<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Asset;

class AssetSeeder extends Seeder
{
    public function run(): void
    {
        $assets = [
            [
                'codigo_activo' => 'ACT-INY-001',
                'nombre' => 'Inyectora de Plástico Engel Victory 250T',
                'descripcion' => 'Inyectora hidráulica monocolor de 250 toneladas para producción de baldes y contenedores plásticos.',
                'categoria' => 'Inyectoras de Plástico',
                'marca' => 'Engel',
                'modelo' => 'Victory 500/250',
                'numero_serie' => 'ENG-2021-9874',
                'especificaciones_tecnicas' => [
                    'Fuerza de Cierre' => '250 Toneladas',
                    'Capacidad de Inyección' => '650 gramos',
                    'Diámetro de Husillo' => '55 mm',
                    'Presión Máxima' => '180 bar',
                    'Potencia Motor' => '45 kW',
                ],
                'ubicacion' => 'Nave A - Inyección Principal',
                'area' => 'Producción Inyección',
                'estado_operativo' => 'Operativo',
                'estado_condicion' => 'Bueno',
                'costo_adquisicion' => 125000.00,
                'fecha_adquisicion' => '2021-06-15',
                'vida_util_estimada' => 15,
                'mtbf_horas' => 340.50,
                'mttr_horas' => 4.20,
                'disponibilidad_porcentaje' => 98.75,
                'qr_code_content' => 'ACT-INY-001',
                'creado_por' => 1,
                'activo' => true,
            ],
            [
                'codigo_activo' => 'ACT-INY-002',
                'nombre' => 'Inyectora de Plástico Haitian Mars II 180T',
                'descripcion' => 'Inyectora servoasistida de 180 toneladas optimizada para alta eficiencia energética en tapas y frascos.',
                'categoria' => 'Inyectoras de Plástico',
                'marca' => 'Haitian',
                'modelo' => 'MA1800II/700',
                'numero_serie' => 'HAI-2022-4412',
                'especificaciones_tecnicas' => [
                    'Fuerza de Cierre' => '180 Toneladas',
                    'Capacidad de Inyección' => '380 gramos',
                    'Diámetro de Husillo' => '45 mm',
                    'Sistema Servo' => 'Haitian Mars Drive',
                ],
                'ubicacion' => 'Nave A - Inyección Línea 2',
                'area' => 'Producción Inyección',
                'estado_operativo' => 'Operativo',
                'estado_condicion' => 'Nuevo',
                'costo_adquisicion' => 88000.00,
                'fecha_adquisicion' => '2022-03-20',
                'vida_util_estimada' => 15,
                'mtbf_horas' => 410.00,
                'mttr_horas' => 2.50,
                'disponibilidad_porcentaje' => 99.40,
                'qr_code_content' => 'ACT-INY-002',
                'creado_por' => 1,
                'activo' => true,
            ],
            [
                'codigo_activo' => 'ACT-GRU-001',
                'nombre' => 'Grúa Puente Bi-Viga Demag 10T',
                'descripcion' => 'Grúa puente aérea de 10 toneladas para cambio seguro y maniobra de moldes de inyección pesados.',
                'categoria' => 'Grúas y Equipos de Izaje',
                'marca' => 'Demag',
                'modelo' => 'EKKE 10t x 18m',
                'numero_serie' => 'DEM-2019-0091',
                'especificaciones_tecnicas' => [
                    'Capacidad Nominal' => '10.000 kg',
                    'Luz de Viga' => '18 metros',
                    'Altura de Izaje' => '6 metros',
                    'Velocidad Elevación' => '6 m/min',
                ],
                'ubicacion' => 'Nave B - Zona de Moldes y Matrices',
                'area' => 'Mantenimiento & Matricería',
                'estado_operativo' => 'Operativo',
                'estado_condicion' => 'Bueno',
                'costo_adquisicion' => 45000.00,
                'fecha_adquisicion' => '2019-11-10',
                'vida_util_estimada' => 20,
                'mtbf_horas' => 520.00,
                'mttr_horas' => 3.10,
                'disponibilidad_porcentaje' => 99.10,
                'qr_code_content' => 'ACT-GRU-001',
                'creado_por' => 1,
                'activo' => true,
            ],
            [
                'codigo_activo' => 'ACT-CMP-001',
                'nombre' => 'Compresor de Tornillo Kaeser BSD 75',
                'descripcion' => 'Compresor de aire comprimido de tornillo rotativo con secador frigorífico integrado para la red neumática de planta.',
                'categoria' => 'Compresores y Neumática',
                'marca' => 'Kaeser',
                'modelo' => 'BSD 75 SFC',
                'numero_serie' => 'KAE-2020-5531',
                'especificaciones_tecnicas' => [
                    'Caudal FAD' => '7.8 m³/min',
                    'Presión Trabajo' => '10 bar',
                    'Potencia Motor' => '45 kW / 60 HP',
                    'Refrigerante' => 'R134a',
                ],
                'ubicacion' => 'Sala de Compresores - Módulo Central',
                'area' => 'Servicios Auxiliares',
                'estado_operativo' => 'Mantenimiento',
                'estado_condicion' => 'Regular',
                'costo_adquisicion' => 38000.00,
                'fecha_adquisicion' => '2020-08-05',
                'vida_util_estimada' => 12,
                'mtbf_horas' => 280.00,
                'mttr_horas' => 6.50,
                'disponibilidad_porcentaje' => 97.20,
                'qr_code_content' => 'ACT-CMP-001',
                'creado_por' => 1,
                'activo' => true,
            ],
            [
                'codigo_activo' => 'ACT-CHL-001',
                'nombre' => 'Chiller Industrial Piovan RTS 120',
                'descripcion' => 'Enfriador de agua helada industrial para refrigeración de moldes de inyección e hidráulica.',
                'categoria' => 'Sistemas de Enfriamiento',
                'marca' => 'Piovan',
                'modelo' => 'RTS 120-2',
                'numero_serie' => 'PIO-2021-3319',
                'especificaciones_tecnicas' => [
                    'Capacidad Frigorífica' => '120 kW (103.200 kcal/h)',
                    'Caudal de Agua' => '20.6 m³/h',
                    'Compresores' => '2x Scroll Copeland',
                ],
                'ubicacion' => 'Sala de Refrigeración Exterior',
                'area' => 'Servicios Auxiliares',
                'estado_operativo' => 'Operativo',
                'estado_condicion' => 'Bueno',
                'costo_adquisicion' => 32000.00,
                'fecha_adquisicion' => '2021-02-18',
                'vida_util_estimada' => 12,
                'mtbf_horas' => 390.00,
                'mttr_horas' => 3.80,
                'disponibilidad_porcentaje' => 98.90,
                'qr_code_content' => 'ACT-CHL-001',
                'creado_por' => 1,
                'activo' => true,
            ],
            [
                'codigo_activo' => 'ACT-TRE-001',
                'nombre' => 'Torre de Enfriamiento Evaporativa Marley NC',
                'descripcion' => 'Torre de agua de circuito abierto para enfriamiento del aceite hidráulico de las inyectoras.',
                'categoria' => 'Sistemas de Enfriamiento',
                'marca' => 'Marley',
                'modelo' => 'NC8401',
                'numero_serie' => 'MAR-2018-8812',
                'especificaciones_tecnicas' => [
                    'Caudal de Agua' => '85 m³/h',
                    'Potencia Ventilador' => '7.5 kW',
                ],
                'ubicacion' => 'Azotea / Exterior Sala Térmica',
                'area' => 'Servicios Auxiliares',
                'estado_operativo' => 'Reparacion',
                'estado_condicion' => 'Malo',
                'costo_adquisicion' => 18500.00,
                'fecha_adquisicion' => '2018-05-10',
                'vida_util_estimada' => 10,
                'mtbf_horas' => 180.00,
                'mttr_horas' => 12.00,
                'disponibilidad_porcentaje' => 93.50,
                'qr_code_content' => 'ACT-TRE-001',
                'creado_por' => 1,
                'activo' => true,
            ],
        ];

        foreach ($assets as $assetData) {
            Asset::updateOrCreate(
                ['codigo_activo' => $assetData['codigo_activo']],
                $assetData
            );
        }
    }
}
