<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SparePart;
use App\Models\InventoryMovement;

class SparePartSeeder extends Seeder
{
    public function run(): void
    {
        $parts = [
            [
                'codigo_sku' => 'REP-MANG-001',
                'nombre' => 'Manguera Hidráulica 3/4" 400 Bar (Alta Presión)',
                'descripcion' => 'Manguera reforzada con malla de acero para circuitos de cierre de inyectoras.',
                'categoria' => 'Hidráulica',
                'marca' => 'Gates',
                'proveedor_principal' => 'Gates Perú S.A.',
                'stock_actual' => 12,
                'stock_minimo' => 5,
                'stock_maximo' => 50,
                'ubicacion_almacen' => 'Estante A2 - Almacén Central',
                'estante' => 'A2',
                'posicion' => 'P-04',
                'costo_unitario' => 45.00,
                'moneda' => 'USD',
                'es_critico' => true,
                'activo' => true,
            ],
            [
                'codigo_sku' => 'REP-FILT-001',
                'nombre' => 'Filtro de Aire Sep. Aceite Kaeser BSD 75',
                'descripcion' => 'Cartucho filtrante desoleador de aire comprimido para sala de compresores.',
                'categoria' => 'Neumática',
                'marca' => 'Kaeser',
                'proveedor_principal' => 'Kaeser Compresores Perú',
                'stock_actual' => 3,
                'stock_minimo' => 4,
                'stock_maximo' => 20,
                'ubicacion_almacen' => 'Estante B1 - Neumática',
                'estante' => 'B1',
                'posicion' => 'P-01',
                'costo_unitario' => 85.00,
                'moneda' => 'USD',
                'es_critico' => true,
                'activo' => true,
            ],
            [
                'codigo_sku' => 'REP-SELL-001',
                'nombre' => 'Juego de Empaquetaduras V-Ring Husillo 55mm',
                'descripcion' => 'Kit de sellos dinámicos en Vitón resistentes a alta temperatura.',
                'categoria' => 'Inyección',
                'marca' => 'SKF',
                'proveedor_principal' => 'SKF del Perú S.A.',
                'stock_actual' => 15,
                'stock_minimo' => 5,
                'stock_maximo' => 40,
                'ubicacion_almacen' => 'Estante A4 - Matricería',
                'estante' => 'A4',
                'posicion' => 'P-12',
                'costo_unitario' => 60.00,
                'moneda' => 'USD',
                'es_critico' => false,
                'activo' => true,
            ],
            [
                'codigo_sku' => 'REP-SENS-001',
                'nombre' => 'Transductor de Presión 0-250 Bar (4-20mA)',
                'descripcion' => 'Sensor electrónico de presión hidráulica para PLC de inyectoras.',
                'categoria' => 'Electricidad & Electrónica',
                'marca' => 'WIKA',
                'proveedor_principal' => 'WIKA Instrumentación S.A.C.',
                'stock_actual' => 2,
                'stock_minimo' => 3,
                'stock_maximo' => 10,
                'ubicacion_almacen' => 'Estante C3 - Instrumentación',
                'estante' => 'C3',
                'posicion' => 'P-08',
                'costo_unitario' => 120.00,
                'moneda' => 'USD',
                'es_critico' => true,
                'activo' => true,
            ],
            [
                'codigo_sku' => 'REP-ACEI-001',
                'nombre' => 'Aceite Hidráulico ISO VG 68 (Cilindro 208L)',
                'descripcion' => 'Lubricante antidesgaste para sistemas hidráulicos industriales.',
                'categoria' => 'Lubricantes',
                'marca' => 'Mobil DTE 26',
                'proveedor_principal' => 'Terpel Perú S.A.C.',
                'stock_actual' => 4,
                'stock_minimo' => 2,
                'stock_maximo' => 10,
                'ubicacion_almacen' => 'Patio de Tambores - Zona Almacén',
                'estante' => 'P1',
                'posicion' => 'P-01',
                'costo_unitario' => 450.00,
                'moneda' => 'USD',
                'es_critico' => true,
                'activo' => true,
            ],
            [
                'codigo_sku' => 'REP-RELE-001',
                'nombre' => 'Relé Auxiliar de Control 24VDC 14 Pines',
                'descripcion' => 'Relé electromagnético compacto con base DIN para tableros eléctricos.',
                'categoria' => 'Electricidad & Electrónica',
                'marca' => 'Omron',
                'proveedor_principal' => 'Electro Industrial S.A.C.',
                'stock_actual' => 25,
                'stock_minimo' => 8,
                'stock_maximo' => 60,
                'ubicacion_almacen' => 'Estante C1 - Electrónica',
                'estante' => 'C1',
                'posicion' => 'P-02',
                'costo_unitario' => 18.50,
                'moneda' => 'USD',
                'es_critico' => false,
                'activo' => true,
            ],
            [
                'codigo_sku' => 'REP-CONT-001',
                'nombre' => 'Contactor de Potencia 3TF44 32A 220VAC',
                'descripcion' => 'Contactor tripolar para arranque de motores de bombas de inyección.',
                'categoria' => 'Electricidad & Electrónica',
                'marca' => 'Siemens',
                'proveedor_principal' => 'Siemens del Perú S.A.',
                'stock_actual' => 6,
                'stock_minimo' => 3,
                'stock_maximo' => 20,
                'ubicacion_almacen' => 'Estante C2 - Motores',
                'estante' => 'C2',
                'posicion' => 'P-05',
                'costo_unitario' => 95.00,
                'moneda' => 'USD',
                'es_critico' => true,
                'activo' => true,
            ],
            [
                'codigo_sku' => 'REP-TERM-001',
                'nombre' => 'Termocupla Tipo J para Boquilla de Inyección',
                'descripcion' => 'Sensor de temperatura con bayoneta de resorte para cañón de calefacción.',
                'categoria' => 'Instrumentación',
                'marca' => 'Marnet',
                'proveedor_principal' => 'Sensores Industriales Perú',
                'stock_actual' => 1,
                'stock_minimo' => 4,
                'stock_maximo' => 15,
                'ubicacion_almacen' => 'Estante C3 - Instrumentación',
                'estante' => 'C3',
                'posicion' => 'P-10',
                'costo_unitario' => 35.00,
                'moneda' => 'USD',
                'es_critico' => true,
                'activo' => true,
            ],
        ];

        foreach ($parts as $partData) {
            $sp = SparePart::updateOrCreate(
                ['codigo_sku' => $partData['codigo_sku']],
                $partData
            );

            if ($sp->movimientos()->count() == 0) {
                InventoryMovement::create([
                    'repuesto_id' => $sp->id,
                    'usuario_id' => 1,
                    'tipo_movimiento' => 'Entrada',
                    'cantidad' => $sp->stock_actual,
                    'stock_anterior' => 0,
                    'stock_nuevo' => $sp->stock_actual,
                    'motivo' => 'Inventario Inicial de Apertura CMMS',
                    'documento_referencia' => 'INV-INICIAL-2026',
                ]);
            }
        }
    }
}
